service: passivo

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  region: eu-west-2
  runtime: python3.6
  environment:
    DYNAMODB_LOG_TABLE: ${self:service}-logs-${opt:stage, self:provider.stage}
    DYNAMODB_PROJECT_TABLE: ${self:service}-projects-${opt:stage, self:provider.stage}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_LOG_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_PROJECT_TABLE}"
  package:
    exclude:
      - tests/**

functions:
  create:
    handler: logs/create.create
    events:
      - http:
          path: log
          method: post
          cors: true

  list:
    handler: logs/list.list
    events:
      - http:
          path: logs
          method: post # all slack slash commands are POST requests
          cors: true

  projects:
    handler: projects/app.handler
    events:
      - http:
          path: projects
          method: post
          cors: true

resources:
  Resources:
    LogsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_LOG_TABLE}
    ProjectsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_PROJECT_TABLE}
